### ISSUE TITLE
Undefined method `buffer_chunk_limit'

### ISSUE THREAD

**Issue by pavgup** [htgc/fluent-plugin-kafka#61]
On line 130 (https://github.com/htgc/fluent-plugin-kafka/blob/master/lib/fluent/plugin/out_kafka_buffered.rb#L130) the out_kafka_buffered.rb file refers to @buffer.buffer_chunk_limit which does not appear to be defined.  However, changing that line to refer to he chunk_limit_size fixes the problem:
```
 max_buffer_size: @buffer.chunk_limit_size / 10, max_buffer_bytesize: @buffer.chunk_limit_size * 2}
```
Being a junior fluent plugin thinker, I'm not confident how this problem is effectively resolved or whether the bug I'm running into is actually a bug.  Eager to give this a discussion to figure out what's right and what's wrong.

**Comment by repeatedly** [comment]
This error happens with v0.14 because v0.14 doesn't provide `@buffer.chunk_limit_size`.
I will change this code for supporting v0.14.

**Comment by pavgup** [comment]
Do you mean v0.14 doesn't include `@buffer.buffer_chunk_limit`?  I changed the plugin to refer to `@buffer.chunk_limit_size` and it comfortably worked.

**Comment by repeatedly** [comment]
> I changed the plugin to refer to @buffer.chunk_limit_size and it comfortably worked.

This code doesn't work with v0.12 :p

**Comment by pavgup** [comment]
Thanks!
