### PR TITLE
Fixing undefined local variable or method: logger

### PR DESCRIPTION
**Pull request by danmx**
Fixing undefine local variable which was introduced in https://github.com/fluent/fluent-plugin-kafka/pull/212

### CODE REVIEW

File: lib/fluent/plugin/in_kafka.rb [hunk 1]
```diff
@@ -174,16 +174,16 @@ def start
     opt[:min_bytes] = @min_bytes if @min_bytes
 
     if @scram_mechanism != nil && @username != nil && @password != nil
-      @kafka = Kafka.new(seed_brokers: @brokers, client_id: @client_id, logger: logger, ssl_ca_cert: read_ssl_file(@ssl_ca_cert),
```
Comment (cosmo0920) [inline lib/fluent/plugin/in_kafka.rb]: How about use `log` instead of removing it?
`Fluent::Plugin` has `log` method.

Comment (danmx) [reply lib/fluent/plugin/in_kafka.rb]: Changed

**Comment by repeatedly** [comment]
Thanks!
